/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Mon Apr 24 16:38:23 PDT 2017
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbPE.h"


/* String declarations */
static std::string const __str_literal_3("%b||%b", 6u);
static std::string const __str_literal_2("-----------", 11u);
static std::string const __str_literal_1("a     ||d", 9u);


/* Constructor */
MOD_mkTbPE::MOD_mkTbPE(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cnt(simHdl, "cnt", this, 7u, (tUInt8)0u, (tUInt8)0u),
    INST_started(simHdl, "started", this, 1u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 7u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbPE::init_symbols_0()
{
  init_symbol(&symbols[0u], "cnt", SYM_MODULE, &INST_cnt);
  init_symbol(&symbols[1u], "cnt__h324", SYM_DEF, &DEF_cnt__h324, 7u);
  init_symbol(&symbols[2u], "RL_count", SYM_RULE);
  init_symbol(&symbols[3u], "RL_finish", SYM_RULE);
  init_symbol(&symbols[4u], "RL_print", SYM_RULE);
  init_symbol(&symbols[5u], "RL_start", SYM_RULE);
  init_symbol(&symbols[6u], "started", SYM_MODULE, &INST_started);
}


/* Rule actions */

void MOD_mkTbPE::RL_start()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s", &__str_literal_1);
    dollar_display(sim_hdl, this, "s", &__str_literal_2);
  }
  INST_started.METH_write((tUInt8)1u);
}

void MOD_mkTbPE::RL_count()
{
  tUInt8 DEF_x__h159;
  DEF_cnt__h324 = INST_cnt.METH_read();
  DEF_x__h159 = (tUInt8)127u & (DEF_cnt__h324 + (tUInt8)1u);
  INST_cnt.METH_write(DEF_x__h159);
}

void MOD_mkTbPE::RL_print()
{
  tUInt8 DEF_out__h192;
  tUInt8 DEF_cnt_BIT_0___h326;
  tUInt8 DEF_cnt_BIT_1___h349;
  tUInt8 DEF_cnt_BIT_2___h372;
  tUInt8 DEF_cnt_BIT_3___h395;
  tUInt8 DEF_cnt_BIT_4___h418;
  tUInt8 DEF_cnt_BIT_5___h441;
  tUInt8 DEF_cnt_BITS_5_TO_0___h239;
  DEF_cnt__h324 = INST_cnt.METH_read();
  DEF_cnt_BITS_5_TO_0___h239 = (tUInt8)((tUInt8)63u & DEF_cnt__h324);
  DEF_cnt_BIT_5___h441 = (tUInt8)((tUInt8)1u & (DEF_cnt__h324 >> 5u));
  DEF_cnt_BIT_4___h418 = (tUInt8)((tUInt8)1u & (DEF_cnt__h324 >> 4u));
  DEF_cnt_BIT_2___h372 = (tUInt8)((tUInt8)1u & (DEF_cnt__h324 >> 2u));
  DEF_cnt_BIT_3___h395 = (tUInt8)((tUInt8)1u & (DEF_cnt__h324 >> 3u));
  DEF_cnt_BIT_1___h349 = (tUInt8)((tUInt8)1u & (DEF_cnt__h324 >> 1u));
  DEF_cnt_BIT_0___h326 = (tUInt8)((tUInt8)1u & DEF_cnt__h324);
  DEF_out__h192 = DEF_cnt_BIT_0___h326 ? (tUInt8)0u : (DEF_cnt_BIT_1___h349 ? (tUInt8)1u : (DEF_cnt_BIT_2___h372 ? (tUInt8)2u : (DEF_cnt_BIT_3___h395 ? (tUInt8)3u : (DEF_cnt_BIT_4___h418 ? (tUInt8)4u : (DEF_cnt_BIT_5___h441 ? (tUInt8)5u : (tUInt8)0u)))));
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s,6,3", &__str_literal_3, DEF_cnt_BITS_5_TO_0___h239, DEF_out__h192);
    dollar_display(sim_hdl, this, "s", &__str_literal_2);
  }
}

void MOD_mkTbPE::RL_finish()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_finish(sim_hdl, "32", 1u);
}


/* Methods */


/* Reset routines */

void MOD_mkTbPE::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_started.reset_RST(ARG_rst_in);
  INST_cnt.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbPE::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbPE::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cnt.dump_state(indent + 2u);
  INST_started.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbPE::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 4u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cnt__h324", 7u);
  num = INST_cnt.dump_VCD_defs(num);
  num = INST_started.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbPE::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbPE &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbPE::vcd_defs(tVCDDumpType dt, MOD_mkTbPE &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 7u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_cnt__h324) != DEF_cnt__h324)
      {
	vcd_write_val(sim_hdl, num, DEF_cnt__h324, 7u);
	backing.DEF_cnt__h324 = DEF_cnt__h324;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_cnt__h324, 7u);
      backing.DEF_cnt__h324 = DEF_cnt__h324;
    }
}

void MOD_mkTbPE::vcd_prims(tVCDDumpType dt, MOD_mkTbPE &backing)
{
  INST_cnt.dump_VCD(dt, backing.INST_cnt);
  INST_started.dump_VCD(dt, backing.INST_started);
}
